version: "3.4"
services:
  worker:
    build: .
    container_name: auto-calling-worker
    restart: always
    environment:
      GROUP_ID_KAFKA: auto-calling
      KAFKA_GROUP_CONSUMER: auto-calling
      KAFKA_SERVER: "localhost:9092"
      KAFKA_TOPIC_ALERT: auto-calling
      MAX_POLL_RECORDS: 1
      MODE: INFO
      MONGODB_DB: auto-calling
      MONGODB_DB_COL: logging
      MONGODB_DB_SOUND_COL: sound
      MONGODB_URI: "mongodb://root:example@localhost:27017/?authMechanism=SCRAM-SHA-1"
      TIME_CALL: 15
      TIME_ZONE: Asia/Bangkok
    volumes:
      - ./sounds:/auto_call/sounds
    network_mode: host