import os

GROUP_ID_KAFKA = os.getenv('GROUP_ID_KAFKA')
KAFKA_GROUP_CONSUMER = os.getenv('KAFKA_GROUP_CONSUMER')
KAFKA_SERVER = os.getenv('KAFKA_SERVER')
KAFKA_TOPIC_ALERT = os.getenv('KAFKA_TOPIC_ALERT')
MAX_POLL_RECORDS = os.getenv('MAX_POLL_RECORDS')
MODE = os.getenv('MODE')
MONGODB_DB = os.getenv('MONGODB_DB')
MONGODB_DB_COL = os.getenv('MONGODB_DB_COL')
MONGODB_DB_SOUND_COL = os.getenv('MONGODB_DB_SOUND_COL')
MONGODB_URI = os.getenv('MONGODB_URI')
TIME_CALL = os.getenv('TIME_CALL')
TIME_ZONE = os.getenv('TIME_ZONE')